# generated by datamodel-codegen:
#   filename:  Ec_passengers_deploymentCheck_if_in_scope_of_applicationDecisionService.yaml
#   timestamp: 2024-07-30T23:05:22+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class EventType(Enum):
    DeniedBoarding = 'DeniedBoarding'
    Cancellation = 'Cancellation'
    Delay = 'Delay'


class Response(BaseModel):
    field__DecisionID__: Optional[str] = Field(
        None,
        alias='__DecisionID__',
        description='Unique identifier representing the execution of the decision service operation. If it is not specified, it will be computed automatically.',
    )
    justification: Optional[str] = None
    regulationApplies: Optional[bool] = None


class Flight(BaseModel):
    departsFromMemberState: Optional[bool] = None
    landsInMemberState: Optional[bool] = None
    operatingAirCarrierIsCommunityCarrier: Optional[bool] = None
    stipulatedCheckInTime: Optional[datetime] = None
    publishedDepartureTime: Optional[datetime] = None


class Status(Enum):
    HasAConfirmedReservation = 'HasAConfirmedReservation'
    HasBeenTransferred = 'HasBeenTransferred'
    Other = 'Other'


class Passenger(BaseModel):
    status: Optional[Status] = None
    presentationForCheckInTime: Optional[datetime] = None


class Fare(Enum):
    FreeOfCharge = 'FreeOfCharge'
    ReducedFareNotAvailableToThePublic = 'ReducedFareNotAvailableToThePublic'
    Other = 'Other'


class Ticket(BaseModel):
    fare: Optional[Fare] = None


class Error(BaseModel):
    code: Optional[int] = Field(None, description='HTTP error code.')
    message: Optional[str] = Field(None, description='Error message.')
    details: Optional[str] = Field(None, description='Detailed error message.')
    errorCode: Optional[str] = Field(None, description='Product error code.')


class Request(BaseModel):
    field__DecisionID__: Optional[str] = Field(
        None,
        alias='__DecisionID__',
        description='Unique identifier representing the execution of the decision service operation. If it is not specified, it will be computed automatically.',
    )
    eventType: Optional[EventType] = None
    flight: Optional[Flight] = None
    passenger: Optional[Passenger] = None
    ticket: Optional[Ticket] = None
