openapi: 3.0.1
info:
  title: Miniloan_ServiceRuleset API
  description: API to invoke the execution of the decision service operation Miniloan_ServiceRuleset.
  version: 1.0.0
servers:
- url: http://localhost:9060/DecisionService/rest
paths:
  /mydeployment/1.0/Miniloan_ServiceRuleset/1.0:
    post:
      summary: Invokes the execution of the decision service operation Miniloan_ServiceRuleset.
      description: Executes the decision service operation Miniloan_ServiceRuleset
        with the path /mydeployment/1.0/Miniloan_ServiceRuleset/1.0.
      operationId: callMiniloan_ServiceRulesetDecisionServiceOperation
      requestBody:
        description: Request for the execution of the decision service operation.
          Contains notably the input parameters that are used for the execution.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        "200":
          description: Response for the execution of the decision service operation.
            Contains notably the output parameters that are returned by the execution.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        default:
          description: Error occurring when invoking the execution of the decision
            service operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Request:
      type: object
      properties:
        __DecisionID__:
          type: string
          description: "Unique identifier representing the execution of the decision\
            \ service operation. If it is not specified, it will be computed automatically."
        borrower:
          $ref: '#/components/schemas/Borrower'
        loan:
          $ref: '#/components/schemas/Loan'
      description: Request for the execution of the decision service operation. Contains
        notably the input parameters that are used for the execution.
    Response:
      type: object
      properties:
        __DecisionID__:
          type: string
          description: "Unique identifier representing the execution of the decision\
            \ service operation. If it is not specified, it will be computed automatically."
        loan:
          $ref: '#/components/schemas/Loan'
      description: Response for the execution of the decision service operation. Contains
        notably the output parameters that are returned by the execution.
    Borrower:
      type: object
      properties:
        name:
          type: string
        creditScore:
          type: integer
          format: int32
        yearlyIncome:
          type: integer
          format: int32
    Loan:
      type: object
      properties:
        amount:
          type: integer
          format: int32
        duration:
          type: integer
          format: int32
        yearlyInterestRate:
          type: number
          format: double
        yearlyRepayment:
          type: integer
          format: int32
        approved:
          type: boolean
        messages:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          description: HTTP error code.
          format: int32
        message:
          type: string
          description: Error message.
        details:
          type: string
          description: Detailed error message.
        errorCode:
          type: string
          description: Product error code.
      description: Error occurring when invoking the execution of the decision service
        operation.
