ibu_assistant:
  assistant_id: ibu_assistant
  #class_name: ibu.llm.assistants.IBU_Assistant.IBUAssistant
  class_name: athena.llm.assistants.BaseAssistant.BaseAssistant
  description: The IBU insurance claim processing assistant
  name: IBU_assistant
  agents: 
    - ibu_agent

ibu_assistant_limited:
  assistant_id: ibu_assistant_limited
  class_name: athena.llm.assistants.BaseAssistant.BaseAssistant
  description: A default assistant that uses LLM, and local defined tools like get borrower, without decision service
  name: IBU Loan App assistant
  agents: 
    - ibu_agent_limited


base_tool_assistant:
  assistant_id: base_tool_assistant
  class_name: athena.llm.assistants.BaseAssistant.BaseAssistant
  description: A default assistant that uses LLM and search tool to do web search
  name: Default tool assistant
  agents: 
    - open_ai_tool

ibu_assistant_lg:
  assistant_id: ibu_assistant_lg
  class_name: ibu.llm.assistants.IBU_Assistant_LG.IBUInsuranceAssistant
  description: The IBU insurance complaint processing assistant
  name: IBU Stateful Assistant Limited
  agents: 
    - ibu_classify_query_agent
    - ibu_tool_rag_agent_limited
    - ibu_tool_rag_agent

ibu_assistant_lg_limited:
  assistant_id: ibu_assistant_lg_limited
  class_name: ibu.llm.assistants.IBU_Assistant_LG.IBUInsuranceAssistant
  description: The IBU insurance complaint processing assistant with no decision service
  name: IBU Assistant Limited
  agents:
    - ibu_classify_query_agent
    - ibu_tool_rag_agent_limited
    - ibu_tool_rag_agent_limited