# Copyright 2024 Athena Decision Systems
# @author Jerome Boyer
# IBU Loan Application Demo
# ------------------------------------------------------------------
tavily:
  tool_id: tavily
  tool_class_name: langchain_community.tools.tavily_search.TavilySearchResults
  tool_description: 'A search engine optimized for comprehensive, accurate, and trusted results'
  tool_fct_name: ''
  tool_id: tavily
  tool_name: "tavily search"


ibu_client_by_name:
  tool_id: ibu_client_by_name
  tool_class_name: ''
  tool_description: 'get client information given his or her name'
  tool_fct_name: get_client_by_name
  tool_name: "get client by name"

ibu_best_action:
  tool_id: ibu_best_action
  tool_class_name: ''
  tool_description: 'perform the next best action given the current state of the loan application knowing\nits unique claim_id and the current client motivation.\nextract the  client motive and if he has the intention to leave'
  tool_fct_name: define_next_best_action_with_decision
  tool_name: "define_next_best_action_with_decision"