# Copyright 2024 Athena Decision Systems
# @author Jerome Boyer
# IBU Loan Application Demo
# ------------------------------------------------------------------
openai_chain_tool:
  agent_id: openai_chain_tool
  name: open_ai_gpt35
  description: openai based agent with prompt coming from langchain hub  and tool
  class_name: athena.llm.agents.base_chain_agent.OwlAgent
  modelName: gpt-3.5-turbo-0125
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: hwchase17/openai-functions-agent
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - tavily


ibu_agent:
  agent_id: ibu_agent
  name: ibu_agent
  description: openai based agent with IBU loan app prompt and tools
  class_name: athena.llm.agents.base_chain_agent.OwlAgent
  modelName: gpt-3.5-turbo-0125
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: ibu_loan_prompt
  # hwchase17/react-chat-json 
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - ibu_client_by_name
  - ibu_loan_assessment_action

ibu_agent_limited:
  agent_id: ibu_agent_limited
  name: ibu_agent
  description: openai based agent with IBU loan app prompt without decision service
  class_name: athena.llm.agents.base_chain_agent.OwlAgent
  modelName: gpt-3.5-turbo-0125
  modelClassName: langchain_openai.ChatOpenAI
  prompt_ref: ibu_loan_prompt
  # hwchase17/react-chat-json 
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - ibu_client_by_name
