open_ai:
  agent_id: open_ai_gpt35
  name: open_ai_gpt35
  description: openai based agent with simple prompt 
  class_name: athena.llm.agents.agent_openai.OpenAIAgent
  modelName: gpt-3.5-turbo-0125
  prompt_ref: default_prompt
  temperature: 0
  top_k: 1
  top_p: 1

ibu_open_ai_tool:
  agent_id: ibu_open_ai_tool
  name: ibu_open_ai_tool
  description: openai based agent with tool to support ibu insurance demo and variable model 
  class_name: ibu.llm.agents.openai_agent_tool.OpenAIAgent
  modelName: gpt-3.5-turbo-0125
  prompt_ref: openai_insurance_with_tool
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - ibu_client_by_id

anthropic_claude_3:
  agent_id: anthropic_claude_3
  name: anthropic_claude_3
  class_name: athena.llm.agents.agent_anthropic.AnthropicAgent
  modelName: claude-3-opus-20240229
  prompt_ref: default_prompt
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - tavily

ibu_agent:
  agent_id: ibu_agent
  name: ibu_agent
  description: openai based agent withIBU prompt and tools
  class_name: ibu.llm.agents.IBU_Agent.IBUAgent
  modelName: gpt-3.5-turbo-0125
  prompt_ref: openai_insurance_with_tool
  temperature: 0
  top_k: 1
  top_p: 1
  tools:
  - ibu_client_by_id
  - ibu_client_by_name
  - ibu_claim_by_id
  - ibu_best_action
