ibu_assistant:
  assistant_id: ibu_assistant
  #class_name: ibu.llm.assistants.IBU_Assistant.IBUAssistant
  class_name: athena.llm.assistants.BaseAssistant.BaseAssistant
  description: The IBU insurance claim processing assistant
  name: IBU_assistant
  agent_id: ibu_agent

ibu_assistant_limited:
  assistant_id: ibu_assistant_limited
  class_name: athena.llm.assistants.BaseAssistant.BaseAssistant
  description: A default assistant that uses LLM, and local defined tools like get borrower, without decision service
  name: IBU Loan App assistant
  agent_id: ibu_agent_limited


base_tool_assistant:
  assistant_id: base_tool_assistant
  class_name: athena.llm.assistants.BaseAssistant.BaseAssistant
  description: A default assistant that uses LLM and search tool to do web search
  name: Default tool assistant
  agent_id: open_ai_tool

ibu_assistant_LG:
  assistant_id: ibu_assistant_LG
  class_name: ibu.llm.assistants.IBU_Assistant_LG.IBUInsuranceAssistant
  description: The IBU insurance complaint processing assistant
  name: IBU_assistant_LG
  agent_id: ibu_tool_rag_agent

