logging_level: INFO
version: 0.0.2
owl_env_path: ../.env
owl_agent_llm_client_class: ibu.llm.agent_openai.OpenAIClient
owl_agent_llm_model: gpt-3.5-turbo-0125


# owl_agent_llm_client_class: athena.llm.agent_anthropic.AnthropicClient

# NOT used owl_agent_decision_service_fct_name: athena.itg.decisions.next_best_action_ds_client.callDecisionService
owl_best_action_ds_url: http://decisionsvc:9060/DecisionService/rest/v1/ComplaintHandling/1.0/nextBestAction
owl_glossary_path: /app/config/glossary.json
owl_prompts_path: /app/config/prompts.json
owl_prompts_key_name: openai_insurance_with_tool
owl_agent_content_vstore_url: http://localhost:8005
owl_agent_content_collection_name: ibu_insurance
owl_agent_content_file_path: /app/file_content
owl_agent_vs_path: /app/chromadb
owl_agent_vs_embedding_fct: OpenAIEmbeddings
owl_agent_llm_history_length: 5
app_insurance_client_repository: ibu.itg.ds.insurance_client_repo_datamgr.InsuranceClientFromDataMgr
app_insurance_claim_repository: ibu.itg.ds.insurance_claim_repo_datamgr.InsuranceClaimFromDataMgr
app_insurance_backend_url: http://datamgr:8080/repository



owl_agent_decision_service_fct_name: ibu.itg.decisions.next_best_action_ds_client.callDecisionService

watsonx_ai_url: https://us-south.ml.cloud.ibm.com
watsonx_ai_project_id: bddd370f-77c3-4b6e-a18b-3ef7f4ca1bae
watsonx_ai_model: "ibm/granite-13b-instruct-v2"